[2023-11-23T23:32:23.034+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table manual__2023-11-23T23:27:20.345802+00:00 [queued]>
[2023-11-23T23:32:23.040+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table manual__2023-11-23T23:27:20.345802+00:00 [queued]>
[2023-11-23T23:32:23.040+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-11-23T23:32:23.049+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-11-23 23:27:20.345802+00:00
[2023-11-23T23:32:23.053+0000] {standard_task_runner.py:57} INFO - Started process 555 to run task
[2023-11-23T23:32:23.056+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_postgres_table', 'manual__2023-11-23T23:27:20.345802+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp1n857fsw']
[2023-11-23T23:32:23.059+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask create_postgres_table
[2023-11-23T23:32:23.103+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator.create_postgres_table manual__2023-11-23T23:27:20.345802+00:00 [running]> on host 1f846b33469f
[2023-11-23T23:32:23.174+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='harsha' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T23:27:20.345802+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T23:27:20.345802+00:00'
[2023-11-23T23:32:23.175+0000] {sql.py:274} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dag_runs (
            dt date ,
            dag_id character varying,
            primary key (dt, dag_id))
           
            
[2023-11-23T23:32:23.184+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-11-23T23:32:23.193+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-11-23T23:32:23.206+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2023-11-23T23:32:23.217+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator, task_id=create_postgres_table, execution_date=20231123T232720, start_date=20231123T233223, end_date=20231123T233223
[2023-11-23T23:32:23.224+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 54 for task create_postgres_table (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 555)
[2023-11-23T23:32:23.271+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T23:32:23.291+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
