[2023-11-23T20:06:32.278+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.loading_data_from_csv_to_postgrestable manual__2023-11-23T20:01:28.843179+00:00 [queued]>
[2023-11-23T20:06:32.285+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.loading_data_from_csv_to_postgrestable manual__2023-11-23T20:01:28.843179+00:00 [queued]>
[2023-11-23T20:06:32.285+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-11-23T20:06:32.295+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): loading_data_from_csv_to_postgrestable> on 2023-11-23 20:01:28.843179+00:00
[2023-11-23T20:06:32.299+0000] {standard_task_runner.py:57} INFO - Started process 2923 to run task
[2023-11-23T20:06:32.303+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'loading_data_from_csv_to_postgrestable', 'manual__2023-11-23T20:01:28.843179+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpl8ccimpw']
[2023-11-23T20:06:32.306+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask loading_data_from_csv_to_postgrestable
[2023-11-23T20:06:32.353+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator.loading_data_from_csv_to_postgrestable manual__2023-11-23T20:01:28.843179+00:00 [running]> on host e7b0b9311e50
[2023-11-23T20:06:32.431+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='harsha' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='loading_data_from_csv_to_postgrestable' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T20:01:28.843179+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T20:01:28.843179+00:00'
[2023-11-23T20:06:32.432+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_operator.py", line 11, in load_csv_to_postgres
    with open('Airflow_Docker/sample_data.csv', mode='r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Airflow_Docker/sample_data.csv'
[2023-11-23T20:06:32.443+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator, task_id=loading_data_from_csv_to_postgrestable, execution_date=20231123T200128, start_date=20231123T200632, end_date=20231123T200632
[2023-11-23T20:06:32.452+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task loading_data_from_csv_to_postgrestable ([Errno 2] No such file or directory: 'Airflow_Docker/sample_data.csv'; 2923)
[2023-11-23T20:06:32.475+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T20:06:32.493+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
